# Generated by Django 4.1.3 on 2022-11-03 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=128)),
                ('is_true', models.BooleanField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.step')),
            ],
        ),
    ]
