# Generated by Django 4.1.3 on 2022-11-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='condition',
            field=models.JSONField(default={}, verbose_name="условие задания в 'pretty' формате"),
            preserve_default=False,
        ),
    ]
